sping:
    cloud:
        gateway:
            routes:
                - id: r1
                  uri: http://localhost:8081/
                  predicates:
                    - path= /customers/**
                - id: r2
                  uri: http://localhost:8082/
                  predicates:
                    - path= /products/**
            discovery:
             locator:
              enabled: false
    application:
     name: gateway-service
server:
    port: 8887